### ISSUE TITLE
No quick save keystroke (e.g. Alt-F,S or Ctrl+S)

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#10]
Those of us who are in the habit of quickly saving our code as we type by pressing Alt-F and S or Ctrl+S will be shocked to find that neither of those actually save anything. 

Suggestion: Adding keyboard accelerators for File / Save would Save programmers a lot of lost time when DDE gets into a mode that prevents us from saving.

**Comment by cfry** [comment]
Good idea! Cmd-S  (for Mac) and Ctrl-S (for windows) now saves files.
I recommend checking the "Save on Eval" checkbox in the 
Output pane header to auto save when you click the Eval button.
I rarely choose Save explicitly.
Occasionally I lose a line or two but since I Eval at least every minute
of coding, rarely is it much.
