### ISSUE TITLE
Dexter can't receive instructions right after turning on

### ISSUE THREAD

**Issue by cfry** [cfry/dde#17]
When trying to run a DDE Job that
  sends instructions to a robot right after
 turning the robot on,  a bad error happens
  that's hard to recover from.
James H didn't recall this happening in the 
robot's that have "the dance", maybe simply because
when the robot is dancing, the operator
knows not to attempt to send something to
the robot.
In any case, waiting a while after turning
dexter on (a minute? not sure)
it seems to be ok.
So that's the workaround.
But this is just a workaround, we can't
expect our users to do this.
We need some kind of a signal from
Dexter to DDE, or for DDE to do some
kind of polling , or simply having
Dexter handling gracefully instructions
when its not quite ready to.

**Comment by cfry** [comment]
Mostly fixed in DDE 2.3.9 with a 
ping request to Dexter before DDE sends its first instruction.
If ping fails, the user gets an explicit error message.
Also, Dexter software that contains the startup "dance"
(which includes the software on most non-Haddington-internal Dexter's,
has reliable connection between Dexter and DDE  after the dance completes.
We are still seeing a few cases where ping takes a long time (ie 1 minute or more]
but it appears that these are odd network issues not related to DDE or Dexter software.

**Comment by JamesNewton** [comment]
Hang on. There are networks which do not allow ping traffic. Ping uses TCP/ICMP.  Internet Control Message Protocol (ICMP). And ICMP does have security related implications. E.g. malware can ping each address in the local net to figure out which IP's actually lead to a device. There are other issues as well. Allowing "Destination Unreachable" responses (ICMP type 3) will allow an external hacker to map your internal network. A very tight corporate network will simply block all external ICMP traffic, and may block internal as well. A better admin will block /some/ ICMP types and allow others. I block all external, and all but Echo (used by ping) and MTU internal. 
http://www.rikfarrow.com/Network/net0700.html

I would recommend changing this so that if the ping fails the user gets a /warning/ and can choose to continue anyway. It is very easy to find yourself in a network were changes to the network config are simply impossible. As a rather embarrassing example, I've completely forgotten the password for my firewall and CAN'T change it without hacking into it to reset the password, which is a major pain in the butt. And I'm fairly competent (he says) imagine a large corporation where a nervous / novice network admin is unwilling to change anything for fear of being hacked or the change having unwanted consequences.

In fact, just letting it try pings and timeout over a few seconds and then continuing would probably be enough. If the user sent a job with the arm off, he will figure that out on his own. If he turned on the arm and immediately sent a job, then if ping works, the job can start the instant the arm is ready. If it fails, then the timeout still gives the arm time to fire up. The only disadvantage is that in a network were ICMP Echo (ping) is disabled, every job will timeout and be delayed for a few seconds. This is infinitely better than just failing. Perhaps a config option to disable the ping on those networks if they are found. 

Best option: Ping for as long as it takes Dexter to come up, and continue anyway if you haven't seen a response.
