### ISSUE TITLE
Cal saving blank AdcCenters.txt files

### ISSUE THREAD

**Issue by JamesWigglesworth** [cfry/dde#24]
If Cal can't read the <strike>AxisCal.txt</strike> AdcCenters.txt file from the robot but can still write to it, the file it creates will have all 0's in it except the center for the current joint.

Also a "save as" button should be added for the option to save the file somewhere besides on the robot.

**Comment by JamesNewton** [comment]
Suggestion: Update the code to save each joints center point separately (in an array) as the user clicks on it, and only save once ALL are non-zero. Even if read fails, the user can't screw up the settings. 

Suggestion: Automatically save a copy of AdcCenters.txt in the dde_apps folder. If read fails, recover from there with warning. 

Also, updating to the HTTP file transfer is critical so read issues don't happen. #26

**Comment by JamesNewton** [comment]
The ability to write files to Dexter via the socket data system has been added to DexRun.c:
https://github.com/HaddingtonDynamics/Dexter/commit/ef39cfe6effd36faeb9bd96b21a11a3dcd6b84ef

DDE needs to be updated to only transfer 244 characters because of command overhead on the 255 byte buffer. E.g. in:
https://github.com/cfry/dde/blob/master/robot.js#L1479
let max_content_chars = 252 
needs to be
let max_content_chars = 244

And then after some testing of the Dexter.send_to_robot command
https://github.com/HaddingtonDynamics/Dexter/wiki/write-to-robot
The Calibration routine can be updated to save the file directly after the user has clicked on each axis and punched in the center of the eye. 

This will not resolve #26 but it will write a correct AdcCenters.txt file if the user specifies all the centers during calibration.

**Comment by JamesNewton** [comment]
I believe this was resolved in later versions of DDE. Any reason why we haven't closed the issue?

**Comment by cfry** [comment]
grrrr lets bring up at our Software meeting call.
Sounds like we did.

**Comment by JamesNewton** [comment]
This should be fixed in the current LTS 2.5.8
